###############################################
# MoveIt Servo Configuration for Streaming Mode
###############################################

use_gazebo: false

## Properties of incoming commands
command_in_type: "speed_units"
scale:
  linear:  0.4
  rotational:  0.8
  joint: 0.5

## Properties of outgoing commands
publish_period: 0.02
low_latency_mode: true

# Topic names
command_out_topic: /servo_node/command
command_out_type: trajectory_msgs/JointTrajectory

publish_joint_positions: true
publish_joint_velocities: false
publish_joint_accelerations: false

## Plugins for smoothing outgoing commands
smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
is_primary_planning_scene_monitor: true

## MoveIt properties
move_group_name: dummy_arm
planning_frame: base_link

## Other frames
ee_frame_name: link6_1_1
robot_link_command_frame: base_link

## Stopping behaviour
incoming_command_timeout: 0.1
num_outgoing_halt_msgs_to_publish: 4

## Configure handling of singularities and joint limits
lower_singularity_threshold: 1000000.0
hard_stop_singularity_threshold: 2000000.0
joint_limit_margin: 0.1
leaving_singularity_threshold_multiplier: 2.0

## Topic names
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status

## Collision checking
check_collisions: false
collision_check_rate: 10.0
self_collision_proximity_threshold: 0.001
scene_collision_proximity_threshold: 0.002
